version: '3.8'
services:
  app:
    build: ./backend
    image: autparthub-app:prod
    container_name: autparthub-app-prod
    restart: unless-stopped
    working_dir: /var/www
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite
    volumes:
      - ./backend:/var/www
    depends_on:
      - nginx
  nginx:
    image: nginx:alpine
    container_name: autparthub-nginx-prod
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www
      - ./backend/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app 