[variables]
NODE_VERSION = "20"

[phases.setup]
nixPkgs = ["nodejs_20", "php82", "php82Packages.composer"]

[phases.install]
cmds = [
  "npm ci",
  "cd backend && composer install --no-dev --optimize-autoloader"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "cd backend && php artisan serve --host=0.0.0.0 --port=$PORT"