[phases.setup]
nixPkgs = ['nodejs', 'php82', 'php82Packages.composer']

[phases.install]
cmds = [
  'cd backend && composer install --no-dev --optimize-autoloader',
  'npm ci'
]

[phases.build]
cmds = [
  'npm run build'
]

[start]
cmd = 'cd backend && php artisan serve --host=0.0.0.0 --port=$PORT'