[build]
builder = "nixpacks"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
startCommand = "cd backend && php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

# Explicitly disable Docker and force nixpacks
[variables]
DISABLE_DOCKER = "true"
NO_DOCKER = "true"
NIXPACKS_NO_DOCKER = "true"
FORCE_NIXPACKS = "true"
BUILDER = "nixpacks"