[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3