version: '3.8'

services:
  app:
    build: .
    image: autparthub-app
    container_name: autparthub-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite
    ports:
      - "9000:9000"

  nginx:
    image: nginx:alpine
    container_name: autparthub-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app 