[variables]
NODE_VERSION = "20"
PHP_VERSION = "8.2"
DISABLE_DOCKER = "true"

[phases.setup]
nixPkgs = ["nodejs_20", "php82", "php82Packages.composer"]

[phases.install]
cmds = [
  "npm ci --prefer-offline --no-audit",
  "cd backend && composer install --no-dev --optimize-autoloader --no-interaction"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "cd backend && php artisan serve --host=0.0.0.0 --port=$PORT"