name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, json, pdo, bcmath, zip
          coverage: none
          
      - name: Verify PHP installation
        run: php --version
          
      - name: Copy testing environment file
        run: cp backend/.env.testing backend/.env
        
      - name: Verify environment file
        working-directory: backend
        run: cat .env
          
      - name: Install Composer dependencies
        working-directory: backend
        run: composer install --no-interaction --prefer-dist --optimize-autoloader --no-scripts
        
      - name: Set directory permissions
        working-directory: backend
        run: chmod -R 775 storage bootstrap/cache
        
      - name: Clear config cache
        working-directory: backend
        run: php artisan config:clear
        
      - name: Run migrations
        working-directory: backend
        run: php artisan migrate --force
        
      - name: Run tests
        working-directory: backend
        run: php artisan test

  frontend-tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Clear npm cache
        run: npm cache clean --force
        
      - name: Remove node_modules and package-lock
        run: rm -rf node_modules package-lock.json
        
      - name: Install dependencies
        run: npm install
        
      - name: Run tests
        run: npm test -- --run
        
      - name: Build frontend
        run: npm run build