name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      sqlite:
        image: nouchka/sqlite3:latest
        ports:
          - 3306:3306
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build backend Docker image
        run: docker compose -f backend/docker-compose.yml build
      - name: Copy .env.ci to .env
        run: cp .env.ci backend/.env
      - name: Install Composer dependencies
        working-directory: backend
        run: composer install --no-interaction --prefer-dist --optimize-autoloader
      - name: Generate Laravel application key
        working-directory: backend
        run: php artisan key:generate
      - name: Set directory permissions
        working-directory: backend
        run: chmod -R 775 storage bootstrap/cache
      - name: Run migrations
        working-directory: backend
        run: php artisan migrate:fresh --seed
      - name: Run tests
        working-directory: backend
        run: php artisan test
